# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias update_zshrc="chezmoi add .zprezto/runcoms/zshrc"

export VISUAL=vim
export EDITOR="$VISUAL"

eval "$(~/.local/bin/mise activate zsh)"
