# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

. /opt/homebrew/opt/asdf/libexec/asdf.sh

alias update_zshrc="chezmoi add .zprezto/runcoms/zshrc"

